USE MikanAttendance;

CREATE TABLE IF NOT EXISTS User (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RealName VARCHAR(32) NOT NULL,
    UserPass VARCHAR(128) NOT NULL,
    Phone VARCHAR(128),
    Email VARCHAR(128),
    UserType ENUM('PM', 'HR', 'SALES', 'OTHERS') NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Salary (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID) REFERENCES User(ID) ON DELETE CASCADE,
    PayDay INT UNSIGNED NOT NULL,
    Salary INT UNSIGNED NOT NULL,
    Remark VARCHAR(1024)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Suggestion (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(128) NOT NULL,
    Content VARCHAR(1024)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProductOrder (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	UserID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID) REFERENCES User(ID) ON DELETE CASCADE,
    OrderSide VARCHAR(256) NOT NULL,
    Product VARCHAR(256) NOT NULL,
    SubmitDate INT UNSIGNED NOT NULL,
    EndDate INT UNSIGNED NOT NULL,
    Remark VARCHAR(1024)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Attendance (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID) REFERENCES User(ID) ON DELETE CASCADE,
    AttendanceTime INT UNSIGNED NOT NULL,
    AttendanceStatus ENUM('ON_TIME', 'LATE', 'OUT_OF_RANGE'),
    AttendanceType TINYINT(1),
    Remark VARCHAR(1024)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;